### ISSUE TITLE
Light and dark theme changes are broken when using a custom app 

### ISSUE THREAD

**Issue by SeeringPhil** [firecmsco/firecms#495] opened 2023-04-17 16:10 UTC
Will try to create a repro repo eventually but basically self explanatory: 

When using the custom components and utilities, and not simply FirebaseCMSApp alone, clicking on the theme change button only changes the background of the scrollbars and not the rest of the application... until a page refresh! 

So basically, if the user clicks on the button they need to refresh the page for the theme toggle to complete properly.

**Comment by OskarGroth** [comment] 2023-11-08 14:27
The issue is here:

https://github.com/firecmsco/firecms/blob/029f3f641be99d6241a4ad827190e8a4ccea5cbe/example/src/docs/CustomCMSApp.tsx#L104

The hook needs to depend on the theme mode to reload.

Can be fixed as such:

```
  const theme = useMemo(
    () => createCMSDefaultTheme({ mode: modeController.mode }),
    [modeController.mode]
  );
```

**Comment by fgatti675** [comment] 2024-03-14 00:39
This was fixed in the latest version. Thanks!

**Closed by fgatti675** 2024-03-14 00:39 UTC
