### ISSUE TITLE
Requests to my server return a 403 since the update to 3.0.0

### ISSUE THREAD

**Issue by VCSJacob** [firecmsco/firecms#612] opened 2024-01-25 22:10 UTC
The update to 3.0.0 causes the AUTH request headers to be sent as a FireCMS authenticated user and not the Firebase authenticated user in the app where my server and a few other client-side apps make requests.
 ```
 // CMS
  const auth = getAuth();
// User Object 
  const user = auth.currentUser;
  
    const fetchRequest = async (e) => {  
    e.preventDefault();
// This token that is grabbed from the firebase user is not from the correct firebase app since the update to 3.0.0
    const token = user && (await user.getIdToken());
    await fetch(
      "http://localhost:5001/genericEndpointName",
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({ ID: accountNum, Key: accessKey }),
      }
    )
      .then((res) => {
        res.json();
      })
      .catch((error) => {
        alert(error);
      });
  };
  
  
  // Middle-ware on express server that checks token
  // decodes firebase jwt provided by firebase auth, stops un-authenticated API request
async function decodeIDToken(req, res, next) {
  if (req.headers?.authorization?.startsWith("Bearer ")) {
    const idToken = req.headers.authorization.split("Bearer ")[1];
    try {
      const decodedToken = await admin.auth().verifyIdToken(idToken);
      req["currentUser"] = decodedToken;
    } catch (err) {
      console.error("Error decoding token:", err);
      res.sendStatus(403);
    }
  }
  next();
}

app.use(decodeIDToken);

 ```

**Comment by fgatti675** [comment] 2024-01-29 14:31
Hi @VCSJacob thank you for reporting. This is caused by the default Firebase instance now pointing to our own project. 
I will look into how to change it to the client one

**Comment by VCSJacob** [comment] 2024-01-31 19:53
This created a new error, I cannot sign into the CMS now at all, the sign-in with google button does not work when clicked nothing happens at all. This is without defining the backendApiHost. 

When I add the backendApiHost prop to the FireCMSApp the CMS just hangs with a spinner that says, "backend loading". 
```
import React from "react"
import { FireCMSApp } from "firecms";
import appConfig from "./index";

function App() {
    return <FireCMSApp
        projectId={"vcs-reads-dev2"}
        appConfig={appConfig}
        backendApiHost={"http://10.0.2.2:5001/vcs-reads-dev2/us-central1/app"}
    />;
}

export default App
```
I even tried to create a new project and start over, still not able to sign in.

**Comment by fgatti675** [comment] 2024-01-31 23:32
Sorry about that, it was an error on our side. Fixed in the latest version.
The `backendApiHost` prop should be left empty. It is the url that connects to our backend.

**Closed** 2024-01-31 23:59 UTC
